# Dockerfile para la imagen de la base de datos PostgreSQL

FROM postgres:16.2-bullseye

# Establecer variables de entorno para la base de da
ENV POSTGRES_DB=projecto
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=Ec94
