name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker-compose up --build 
          docker-compose exec web sh -c "while ! nc -z db 5432; do sleep 1; done"

      - name: Apply Django migrations
        run: |
          docker-compose exec web python manage.py migrate
        continue-on-error: true  # Continuar si hay un error

      - name: Show Docker Compose logs
        run: |
          docker-compose logs
