name: Docker Compose Connectivity Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  connectivity-check:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:latest
        options: --privileged
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        
      - name: Build Docker images
        run: docker-compose build
        
      - name: Start services
        run: docker-compose up -d
        
      - name: Check web service connectivity to database
        run: |
          DATABASE_USER=$DATABASE_USER
          DATABASE_NAME=$DATABASE_NAME
          docker-compose exec web sh -c "sleep 10 && psql -h $DATABASE_HOST -U $DATABASE_USER $DATABASE_NAME"
        
      - name: Check pgadmin connectivity to database
        run: |
          DATABASE_USER=$DATABASE_USER
          DATABASE_NAME=$DATABASE_NAME
          docker-compose exec pgadmin sh -c "sleep 10 && psql -h $DATABASE_HOST -U $DATABASE_USER $DATABASE_NAME"
        
      - name: Stop services
        run: docker-compose down
