name: Verify database population

on:
  pull_request:
    branches:
      - main

jobs:

  build_and_push:
    runs-on: ubuntu:latest

    steps:
      - name: Build and push images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker-compose build
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker-compose push
