name: Check if tables are populated

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-persistence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start Docker services
        run: |
          docker-compose up -d
          docker-compose ps

      - name: Wait for database container to start
        run: |
          until docker-compose exec db bash -c 'echo "Conexión establecida"'; do
            echo "Esperando a que la base de datos esté disponible..."
            sleep 1
          done

      - name: Enter container and check tables
        run: |
          docker-compose exec db bash -c '
            ls &&
            find / -name psql &&
            /usr/bin/psql -U postgres -d projecto -c "\dt" &&
            for table in "auctions" "artworks" "customers" "bids" "admins"; do
              if /usr/bin/psql -U postgres -d projecto -c "SELECT COUNT(*) FROM $table" | grep -q "[1-9][0-9]*"; then
                echo "La tabla $table está poblada"
              else
                echo "Advertencia: La tabla $table está vacía"
              fi
            done
          '

      - name: Stop Docker services
        run: docker-compose down

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push
