name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        # A string to determine the format of the version output
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
            
    - name: Docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        echo "Inicial login"
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin
        echo "Fin del login"
        echo "New version: $NEW_VERSION!!!"
    
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t eviltomato/docker-perseus.reservation.manager:$NEW_VERSION .
        docker build -t eviltomato/docker-perseus.reservation.manager:latest .
        
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push eviltomato/docker-perseus.reservation.manager:$NEW_VERSION
        docker push eviltomato/docker-perseus.reservation.manager:latest
