name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        run: |
          sudo apt update
          sudo apt install -y python3
          sudo apt install -y python3-pip
          pip3 install -r requirements.txt

      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your_image_name:latest .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker push ${{ secrets.DOCKER_USERNAME }}/your_image_name:latest
