name: Check Database Tables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start Docker services
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 30

      - name: Check if tables are populated
        run: |
          docker-compose exec -T db sh -c "PGPASSWORD='${PGADMIN_DEFAULT_PASSWORD}' psql -U 'postgres' -h '${DATABASE_HOST}' -d '${DATABASE_NAME}' -c \"SELECT ...\""

      - name: Stop Docker services
        run: docker-compose down
