name: Check Docker Compose Volumes

on:
  pull_request:
    branches:
      - main

jobs:
  check_volumes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io curl
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Remove conflicting containerd package
      run: sudo apt-get remove -y containerd

    - name: Install containerd.io
      run: |
        sudo apt-get install -y containerd.io

    - name: Validate Docker Compose
      run: docker-compose config -q

    - name: Check for missing volumes
      id: check_volumes
      run: |
        MISSING_VOLUMES=0
        SERVICES=$(docker-compose config --services)
        for SERVICE in $SERVICES; do
          if ! docker-compose config | grep "volumes:" -A 1 | grep -q "$SERVICE"; then
            echo "Missing volumes for service: $SERVICE"
            MISSING_VOLUMES=$((MISSING_VOLUMES + 1))
          fi
        done

        if [ $MISSING_VOLUMES -gt 0 ]; then
          echo "::error::There are missing volumes in the Docker Compose file."
          exit 1
        else
          echo "All services have volumes defined."
        fi

    - name: Build and push images if volumes are defined
      if: ${{ success() }}
      run: |
        docker-compose build
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker-compose push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
