name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  verify_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Este paso obtiene la dirección IP del servicio "db" y la guarda en una variable
      - name: Get Docker container IP
        id: get_container_ip
        run: |
          CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' db)
          echo "::set-output name=container_ip::$CONTAINER_IP"

      - name: Set execute permissions
        run: chmod +x ./auction_app/verify_database.sh

      # En este paso, utilizamos la dirección IP obtenida en el paso anterior para la verificación de la base de datos
      - name: Verify database population
        id: verify_db_pop
        env:
          DATABASE_USER: postgres
          DATABASE_HOST: ${{ steps.get_container_ip.outputs.container_ip }}
          DATABASE_NAME: projecto
        run: ./auction_app/verify_database.sh

      - name: Build and push images
        if: ${{ steps.verify_db_pop.outcome == 'success' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker-compose build
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker-compose push
