name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Load environment variables from .env
        run: |
          source .env

      - name: Build and push Docker images
        env:
          DOCKER_USERNAME: ${DOCKER_USERNAME}
          DOCKER_PASSWORD: ${DOCKER_PASSWORD}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker-compose build
          docker-compose push
