name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run services
        run: |
          docker-compose up --build --detach --detach-keys="ctrl-c"
          docker-compose exec web python manage.py migrate
