name: Check Database Tables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start Docker services
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 30

      - name: Check if tables are populated
        run: |
          docker-compose exec -T db sh -c 'PGPASSWORD=$DATABASE_PASSWORD psql -U $DATABASE_USER -h $DATABASE_HOST -d $DATABASE_NAME -c "SELECT CASE WHEN EXISTS (SELECT 1 FROM auctions) THEN '' ELSE '\''Advertencia: La tabla auctions está vacía'\'' END AS auctions, CASE WHEN EXISTS (SELECT 1 FROM artworks) THEN '' ELSE '\''Advertencia: La tabla artworks está vacía'\'' END AS artworks, CASE WHEN EXISTS (SELECT 1 FROM customers) THEN '' ELSE '\''Advertencia: La tabla customers está vacía'\'' END AS customers, CASE WHEN EXISTS (SELECT 1 FROM bids) THEN '' ELSE '\''Advertencia: La tabla bids está vacía'\'' END AS bids, CASE WHEN EXISTS (SELECT 1 FROM admins) THEN '' ELSE '\''Advertencia: La tabla admins está vacía'\'' END AS admins;"'

      - name: Stop Docker services
        run: docker-compose down
