name: Push Images to Docker Hub

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_run_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker
        run: sudo systemctl start docker

      - name: Build and run container
        run: docker-compose up -d

      # Ejecutar las migraciones de Django
      - name: Run Django migrations
        run: docker-compose exec -T web python manage.py migrate

      # Crear superusuario
      - name: Create superuser
        env:
          DJANGO_SUPERUSER_USERNAME: admin
          DJANGO_SUPERUSER_EMAIL: admin@example.com
          DJANGO_SUPERUSER_PASSWORD: password123
        run: docker-compose exec -T web python manage.py createsuperuser --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL --noinput

      # Verificar la población de la base de datos
      - name: Verify database population
        id: verify_db_pop
        run: ./auction_app/verify_database.sh

      # Verificar el estado de verificación
      - name: Check verification status
        if: steps.verify_db_pop.outputs.populated == 'true'
        run: echo "All tables are populated. Continue with the workflow."

      # Detener el flujo de trabajo si la verificación falla
      - name: Verification failed
        if: steps.verify_db_pop.outputs.populated == 'false'
        run: |
          echo "One or more tables are not populated. Halting the workflow."
          exit 1

  push:
    runs-on: ubuntu-latest
    needs: build_and_run_container  # Esperar a que la construcción y la verificación se completen antes de comenzar

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Etiquetar y subir la imagen del servicio web
      - name: Tag and push web service image
        run: |
          docker tag ervincaravaliibarra/galeria-8:latest ${{ secrets.DOCKER_USERNAME }}/galeria-8-web:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/galeria-8-web:latest

      # Etiquetar y subir la imagen del servicio de base de datos
      - name: Tag and push database service image
        run: |
          docker tag ervincaravaliibarra/bdgaleria-8:latest ${{ secrets.DOCKER_USERNAME }}/galeria-8-db:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/galeria-8-db:latest

      # Etiquetar y subir la imagen del servicio de pgAdmin
      - name: Tag and push pgAdmin service image
        run: |
          docker tag ervincaravaliibarra/pgadmin-galeria-8:latest ${{ secrets.DOCKER_USERNAME }}/galeria-8-pgadmin:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/galeria-8-pgadmin:latest
